// Models/Customer.cs
// Maps to the "Customers" table in MySQL.
// A customer places orders. One customer → many orders.

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrderFlow.API.Models
{
    public class Customer
    {
        // Primary Key — auto-generated by DB
        public int Id { get; set; }

        [Required]
        [MaxLength(150)]
        public string Name { get; set; } = string.Empty;

        // Email must be unique — enforced via HasIndex().IsUnique() in DbContext
        [Required]
        [MaxLength(200)]
        public string Email { get; set; } = string.Empty;

        // Optional contact number
        [MaxLength(15)]
        public string? Phone { get; set; }

        // Delivery address — optional at registration, required at order time
        [MaxLength(400)]
        public string? Address { get; set; }

        // ── Soft Delete Fields ────
        public bool IsDeleted { get; set; } = false;
        public DateTime? DeletedAt { get; set; }

        [MaxLength(100)]
        public string? DeletedBy { get; set; }

        // ── Audit Fields ────
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // ── Navigation Property ────
        // One customer → many orders
        // EF Core uses this to build the FK relationship in the DB
        public ICollection<Order> Orders { get; set; } = new List<Order>();
    }
}